sudo: required

language: java

jdk:
  - oraclejdk8

env:
  global:
    - REPO=jangrott/lnksmgmt_link_service

services:
  - docker

install:\
  - gradle assemble
  - docker build -t $REPO .

before_script:
  - docker run -d -p 9010:9010 $REPO

script:
  - gradle check
  - docker ps | grep -q $REPO

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker push $REPO; fi